export const auditors = [
  {
    id: 1,
    name: "Aniket Security Labs",
    type: "Agency",
    avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=agency1",
    experience: "4+ Years",
    expertise: ["DeFi", "ERC20", "NFT", "Bridge"],
    audits: 32,
    issues: { critical: 14, medium: 36, low: 62 },
    rating: 4.9,
    fee: "1.2 ETH / project",
  },
  {
    id: 2,
    name: "Riya Shah",
    type: "Individual",
    avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=riya",
    experience: "2+ Years",
    expertise: ["Solidity", "ZK Contracts", "Vyper"],
    audits: 14,
    issues: { critical: 4, medium: 10, low: 22 },
    rating: 4.7,
    fee: "0.6 ETH / project",
  },
  {
    id: 3,
    name: "BlockSecure Labs",
    type: "Agency",
    avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=blocksecure",
    experience: "5+ Years",
    expertise: ["DeFi", "Lending", "Staking", "DAOs"],
    audits: 58,
    issues: { critical: 31, medium: 40, low: 91 },
    rating: 4.95,
    fee: "2.0 ETH / project",
  },
];
